apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: task-api
  version: "1.0.0"

commonAnnotations:
  description: "Task API microservice"
  managed-by: "kustomize"

images:
  - name: task-api
    newName: task-api
    newTag: v1
